### ISSUE TITLE
The lib does not support non-bitcoin address types

### ISSUE THREAD

**Issue by karpovep** [cryptocoinjs/btc-address#4]
The lib supports addresses only from mainnet and testnet (bitcoin network). It would be great if it supports other types of addresses (litecoin, dogecoin etc.) or at least it can be configured, but not hardcoded.

**Comment by jprichardson** [comment]
This was intentional as denoted by the `btc-` prefix. However, `btc-address` is deprecated. Look at https://github.com/cryptocoinjs/coinkey or https://github.com/cryptocoinjs/coinstring.
